apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-data-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
{{- if ( and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.frontend.volumes.data.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-uploads-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
{{- if (and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.frontend.volumes.uploads.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-data-claim
  namespace: {{ .Release.Namespace }}
  annotations: {{ .Values.persistence.annotations }}
spec:
{{- if (and .Values.persistence .Values.persistence.storageClassName) }}
  storageClassName: {{ .Values.persistence.storageClassName }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.image.volumes.data.size }}
