apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: openstad-ingress-update-role
rules:
  - apiGroups: ['extensions','networking.k8s.io']
    resources: ['ingresses']
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]
  - apiGroups: ['networking.k8s.io']
    resources: ['ingressclasses']
    verbs: ["get", "list", "watch"]

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: openstad-ingress-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: openstad-ingress-update-rb
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openstad-ingress-update-role
subjects:
  - kind: ServiceAccount
    name: openstad-ingress-sa

---

apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: openstad-secrets-sa

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: secret-creator
rules:
  - apiGroups: ['']
    resources: ['secrets']
    verbs: ["create", "update", "patch", "delete", "get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-creator-role-to-openstad-secrets-sa
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: ''
  kind: Role
  name: secret-creator
subjects:
  - kind: ServiceAccount
    name: openstad-secrets-sa
    namespace: {{ .Release.Namespace }}
