---
{{- if .Values.adminer.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "openstad.adminer.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.adminer.label }}
  ports:
  - name: http
    protocol: TCP
    port: {{ .Values.adminer.service.httpPort }}
  type: ClusterIP
{{- end -}}
