---
dependencies:
- name: cert-manager
  version: "0.15.1"
  repository: "https://charts.jetstack.io"
  condition: dependencies.cert-manager.enabled

- name: mongodb
  version: "13.1.7"
  repository: "https://charts.bitnami.com/bitnami"
  condition: dependencies.mongodb.enabled
  image:
    tag: 5.0.13-debian-11-r5

- name: mysql
  version: "9.4.1"
  repository: "https://charts.bitnami.com/bitnami"
  condition: dependencies.mysql.enabled

- name: common
  version: "2.0.3"
  repository: https://charts.bitnami.com/bitnami