---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-auth-mail
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
  host: {{ .Values.secrets.mail.auth.host | default "mail.example.com" | b64enc }}
  email_assets_url: {{ .Values.secrets.mail.auth.emailAssetsUrl | default "assets.example.com" | b64enc }}
  port: {{ .Values.secrets.mail.auth.port | default 587 | toString | b64enc }}
  user: {{ .Values.secrets.mail.auth.user | default "mail@example.com" | b64enc }}
  password: {{ .Values.secrets.mail.auth.password | default ( randAlphaNum 12 ) | b64enc }}
