---
apiVersion: v1
kind: Secret
metadata:
  name: openstad-cookies
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  cookie_name: {{ .Values.secrets.cookies.cookieName | default "openstad.sid" | b64enc }}
  only_secure: {{ .Values.secrets.cookies.onlySecure | default "true" | b64enc }}
  jwt_secret: {{ .Values.secrets.cookies.jwtSecret | default ( randAlphaNum 12 ) | b64enc }}
