frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:release-latest-merge-w-0-18-0-beta-da8bf01-1666604047
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:release-0.15.12-beta-7597b2c-1462084790
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:feature-gitops-workflow-310003d-527479285
api:
  deploymentContainer:
    image: draadnl/openstad-api:feature-release-choices-guide-result-counter-stats-4ad0041-1489228126
image:
  deploymentContainer:
    image: draadnl/openstad-image-server:release-files-s3-tests-812cf3e-1391832904
