frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:release-enschede-release-141ef7e-8098027248
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:release-veenendaal-allow-multiple-logins-80c132a-7913942220
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:release-wolkenstad-3356c5f-7194819160
api:
  deploymentContainer:
    image: draadnl/openstad-api:release-0.16.2-beta-288264c-8047015790
image:
  deploymentContainer:
    image: draadnl/openstad-image-server:release-files-s3-tests-812cf3e-1391832904
