frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:release-haarlemmermeer-5fdd646-11517214579
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:release-denhaag-044e318-10832655446
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:release-haarlemmermeer-f8155c3-12011157294
api:
  deploymentContainer:
    image: draadnl/openstad-api:release-0.16.1-beta-35e7986-9517792582
image:
  deploymentContainer:
    image: draadnl/openstad-image-server:release-files-s3-tests-812cf3e-1391832904
