frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:release-kaag-668fb1f-7816852360
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:release-veenendaal-allow-multiple-logins-80c132a-7913942220
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:release-wolkenstad-3356c5f-7194819160
api:
  deploymentContainer:
    image: draadnl/openstad-api:release-wolkenstad-20-11-d899a02-7884981342
image:
  deploymentContainer:
    image: draadnl/openstad-image-server:release-files-s3-tests-812cf3e-1391832904
