frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:feature-fix-user-displayname-not-showing-d27ea19-2256662395
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:develop-8c08c08-1663398735
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:feature-gitops-workflow-2fa-80a49f4-2745778639
api:
  deploymentContainer:
    image: draadnl/openstad-api:feature-haarlemmermeer-submission-default-template-4fb0070-5309083930
image:
  deploymentContainer:
    image: draadnl/openstad-image-server:release-files-s3-tests-812cf3e-1391832904
