frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:feature-github-workflow-8d9a1f4-503628237
auth:
  deploymentContainer:
    image: openstad/auth:v0.10.0
admin:
  deploymentContainer:
    image: draadnl/openstad-admin:feature-gitops-workflow-e837e57-503718897
api:
  deploymentContainer:
    image: draadnl/openstad-api:754608218
image:
  deploymentContainer:
    image: openstad/image:v0.7.0
