frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:feature-github-workflow-b1100a2-503801389
auth:
  deploymentContainer:
    image: openstad/auth:v0.10.0
admin:
  deploymentContainer:
    image: draadnl/openstad-admin:feature-gitops-workflow-32b655f-503729968
api:
  deploymentContainer:
    image: draadnl/openstad-api:754608218
image:
  deploymentContainer:
    image: openstad/image:v0.7.0
