frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:release-0.16.0-beta-f2e21db-748198176
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:feature-0.11-fix-double-email-3362160-810459769
admin:
  deploymentContainer:
    image: openstad/admin:v0.14.0
api:
  deploymentContainer:
    image: openstad/api:v0.14.0
image:
  deploymentContainer:
    image: openstad/image:v0.7.0
