# Optional Dependencies

##
## In this block you can toggle all optional dependencies.
## If you want to use an existing database(s) or services, disable
## the chart database(s) here.
##
## - To enable a dependency, set the enabled value of the relevant
##   dependency to true.
##
## - To disable a dependency, set the enabled value of the relevant
##   dependency to false.
##
## Note: If you use an existing database, please change the
##      relevant credentials in secrets.database for MySQL and/or
##      secrets.mongodb for MongoDB
##

dependencies:
  ## Database
  mongodb:
    enabled: true
  mysql:
    enabled: true
  ## SSL
  cert-manager:
    enabled: false
# Internal config
public:
  name: openstad
cert-manager:
  # Whether we want to install CRDs.
  installCRDs: false
clusterIssuer:
  enabled: false
frontend:
  deploymentContainer:
    image: openstad/frontend:749391863
  resources:
    # Max resources
    limits:
      cpu: 2
      memory: 2Gi
    # Min resources
    requests:
      cpu: 100m
      memory: 500M
adminer:
  deploymentContainer:
    image: adminer
auth:
  deploymentContainer:
    image: openstad/auth:v0.8.0
admin:
  deploymentContainer:
    image: openstad/admin:v0.7.4
api:
  deploymentContainer:
    image: draadnl/openstad-api:release-pzh-1.2
image:
  deploymentContainer:
    image: openstad/image:v0.7.0
