frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:master-aa3e24c-6889629205
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:master-7a0f834-9212964817
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:master-8100b66-8660862800
api:
  deploymentContainer:
    image: draadnl/openstad-image-server:master-23658b6-9091969978
image:
  deploymentContainer:
    image: draadnl/openstad-image-server:master-404456a-9092511071
