frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:master-aa3e24c-6889629205
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:master-a7daf98-2971519363
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:master-ea7914d-7611687368
api:
  deploymentContainer:
    image: draadnl/openstad-api:master-f29dbe3-2971535533
image:
  deploymentContainer:
    image: openstad/image:v0.7.2
