frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:master-edcc1d2-2319995638
auth:
  deploymentContainer:
    image: draadnl/openstad-oauth2-server:master-a7daf98-2971519363
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:master-a08526d-2881362271
api:
  deploymentContainer:
    image: draadnl/openstad-api:master-1ab59c8-2102298162
image:
  deploymentContainer:
    image: openstad/image:v0.7.2
