frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:release-0.18.0-beta-4df20d3-1115678893
auth:
  deploymentContainer:
    image: openstad/auth:0.15.10
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:feature-gitops-workflow-310003d-527479285
api:
  deploymentContainer:
    image: draadnl/openstad-api:release-0.16.1-beta-3707464-1093490813
image:
  deploymentContainer:
    image: openstad/image:v0.7.0
