frontend:
  deploymentContainer:
    image: draadnl/openstad-frontend:release-0.13.0-beta-2c20594-571709228
auth:
  deploymentContainer:
    image: openstad/auth:v0.11.0
admin:
  deploymentContainer:
    image: draadnl/openstad-management-panel:feature-gitops-workflow-310003d-527479285
api:
  deploymentContainer:
    image: openstad/api:v0.12.0
image:
  deploymentContainer:
    image: openstad/image:v0.7.0
